# _quarto.yml - Main configuration file
project:
  type: website
  output-dir: docs

website:
  title: "rOpenSci"
  navbar:
    background: primary
    search: true
    left:
      - text: "Inicio"
        file: index.qmd
      - text: "Campeon(a|e)s"
        file: champions/index.qmd
      - text: "Mentor(a|e)s"
        file: mentors/index.qmd
      - text: "Recursos"
        file: resources/resources.qmd
      - text: "Galeria"
        file: galeria/index.qmd
      - text: "FAQs"
        file: resources/faq.qmd

format:
  html:
    theme: [css/extra.scss]
    toc: false



