---
page-layout: custom
section-divs: false
editor: source
---

::: {.hero .grey-border}
::: {.content-block}

::: {.hero-title style="color: #4177ca"}
# Programa de Campeon(a|e)s de rOpenSci
:::

::: {..hero-title}
### Forma parte del programa y súmate a una comunidad global de personas que usan y desarrollan software cientifico y abierto  
:::

::: {.hero-text}
Nuestro programa busca **identificar**, **reconocer** y **premiar** a las personas **líderes** en una comunidad de ciencia abierta, ingeniería de software de investigación y la comunidad de programación R.

Es una plataforma increíble para desarrollar tu proyecto de software libre con apoyo de expertos, interactuar, compartir y fortalecer una red con otras personas decididas a desarrollar la ciencia abierta y reproducible en tu lugar en el mundo. 


::: hero-buttons
[Aplicar como Campeon/a](/champions/apply.qmd){.btn .btn-primary role="button"} [Aplicar como Mentor/a](/mentors/apply.qmd){.btn .btn-primary role="button"}
:::
:::
:::
:::


::: {.content-block }
::: {.features}

::: {.feature}
### Formación
Los participantes reciben capacitacion en la práctica de la ciencia abierta, la ingeniería de software de investigación, la programación en R y la creación y gestión de comunidades.

::: {.learn-more}
[Leer más »](.qmd)
:::
:::

::: {.feature}
### Proyectos
Los participantes desarrollar un proyecto como la creación de nuevos paquetes R o la participación en el proceso de revisión por pares de rOpenSci, ya sea para revisar o para que su paquete sea revisado.

::: {.learn-more}
[Leer más »](.qmd)
:::
:::

::: {.feature}
### Divulgación
Los participantes pueden elegir cómo quieren retribuir a sus propias comunidades e instituciones, ya sea a través de la tutoría o la promoción de prácticas de ciencia abierta y software libre de investigacion.

::: {.learn-more}
[Leer más »](.qmd)
:::
:::

:::
:::

A lo largo de 12 meses, quienes participan reciben formación, tutoría individual para el desarrollo de un proyecto de software libre, un estipendio anual y participan en diversas actividades de construcción y fortalecimiento de comunidades.

Tambien deben desarrollar un proyecto como la creación de nuevos paquetes R o la participación en el proceso de revisión por pares de rOpenSci que les enseña las mejores prácticas para desarrollar y compartir software de investigación y les invita a formar parte de una comunidad internacional

Al final del programa, los participantes pueden elegir cómo quieren retribuir a sus propias comunidades e instituciones, ya sea a través de la divulgación, la tutoría o la promoción de prácticas de ciencia abierta y software libre de investigacion.

Cuando terminan, están plenamente integrados en la comunidad de rOpenSci, que les proporciona apoyo continuo y oportunidades de crecimiento.

Durante los proximos dos años, el programa tendra cohortes centradas en América Latina y que se realizaran completamente en español.

El foco de estas cohortes será fomentar el software de investigación sostenible como pilar de la Ciencia Abierta en América Latina mediante el desarrollo de capacidades y comunidad.

::: {.footer}
::: 
