---
title: "Plantilla para email de apoyo al proyecto"
---

*Asunto*: Apoyo para la participación de _nombre de la persona solicitante_ en el Programa de Campeones/as de rOpenSci

*Texto*: 

Comité de Selección del Programa de Campeon(a|e)s de rOpenSci

Escribo para expresar mi apoyo a la intención de _nombre de la persona solicitante_ de participar en el programa de campeones y campeonas de rOpenSci y contribuir a nuestro paquete de R como su proyecto.

Soy el/la _autor(a)/mantenedor(a)_ del paquete _nombre del paquete_, alojado en _link con url completa al repositorio publico del paquete_ y este correo electrónico es un reconocimiento formal de la intención de _nombre de la persona solicitante_ de contribuir y confirma el apoyo del autor(es) y/o co-mantenedor(es) del paquete a su trabajo si es seleccionado como campeón(a).

Si tiene alguna pregunta, no dude en ponerse en contacto con nosotros.

Un cordial saludo,

_Nombre y cargo de la persona que envia el mail y formas de contacto_
