---
title: "Mentor(a|e)s"
toc: true
toc-location: right
---

## ¿Qué se espera de una Mentora o un Mentor?

Mentores y mentoras desempeñarán un papel fundamental en el programa de rOpenSci, ayudando a seleccionar a los campeones y campeonas y también asesorando e inspirando a quienes mentoreen. Los mentores y mentoras pondrán en contacto a sus campeones/as con personas, programas y organizaciones; recomendarán recursos, lecturas, formación y experiencias; y proporcionarán comentarios sobre el proyecto de su campeón o campeona.  
También pueden ayudar a sus tutelados a realizar otras actividades como: dar una charla, escribir artículos blog, escribir un paper, aplicar a una beca para participar de una conferencia y enseñar a otras personas de la comunidad.

Buscamos personas que:

  * Hayan demostrado comprensión y capacidad para trabajar de forma abierta y colaborativa;

  * Tengan la voluntad de guiar y enseñar a otras personas;

  * Cuenten con experiencia previa en cualquiera de los siguientes campos:

      * Desarrollar, mantener o contribuir a cualquier paquete rOpenSci o paquete que haya pasado por la revisión de rOpenSci, o

      * Participar en el proceso de revisión de rOpenSci, o

      * Desarrollar de paquetes y/o revisión de código entre pares.

Los mentores y mentoras adquirirán experiencia y habilidades para realizar su tarea, 
serán reconocidos en el sitio web de rOpenSci y en los canales de las redes sociales 
y ampliarán su red de contactos internacionales a través de las redes de su cohorte y cohortes anteriores. 
Al tutelar a nuestros campeones y campeonas seleccionados y ayudar a dar forma a este programa, mentoras y mentores también estarán retribuyendo a la comunidad rOpenSci de una forma estupenda y significativa. 
Al finalizar el programa, los mentores recibirán un estipendio de USD 500.

### Expectativas de tiempo y participación

Se espera que el compromiso total de tiempo sea de aproximadamente 3 a 4 horas al mes desde Marzo de 2026 hasta Marzo de 2027 para completar el siguiente calendario tentativo del programa.


|Fecha|Evento|Detalle|Duración|
|----|-----|------|--------| 
|Marzo de 2026|Seleccionar participantes |Revisar, clasificar y seleccionar hasta tres proyectos revisados para ser mentor-a.|2 h|
|Marzo de 2026|Evento de lanzamiento|Conocer el programa, revisar las expectativas del programa y responder preguntas. Conocer al grupo de mentoría.|1,5 h|
|Abril de 2026|Formación|Cómo ser mentor y logística del programa.|2 h|
|Mayo de 2026|Reunirse con los campeones-as|Proporcionar feedback y orientación sobre el proyecto.  Poner en contacto con otras personas expertas, mentores o participantes de la comunidad. Recomendar formación y recursos para el proyecto del campeon-a. Una reunión al mes.| 0,5 h|
|Mayo de 2026| Los campeones presentarán su proyecto y recibirán comentarios. |1,5 horas|
|De Mayo a Septiembre de 2026.|  Conectar con otros expertos, mentores o miembros de la comunidad. Recomendar formación y recursos para el proyecto. | 0,5 h |
|Agosto de 2026 Reunión de cohorte [opcional]| Reflexiones sobre los proyectos. Se invitará a los participantes a compartir con la cohorte las conclusiones de sus proyectos. |  1,5 h|
|Diciembre de 2026 | Reflexiones sobre el programa. Se invitará a los mentores a compartir sus experiencias con la cohorte.|.|1,5h|
|Marzo de 2027 |Fin del programa| Cierre de la cohorte y definición de las nuevas funciones de los campeones y los mentores. Entrevista de evaluación |2 h|

## Beneficios de ser mentor/a

Al convertirte en parte del equipo de mentores de rOpenSci podrás:

* Empoderar a otras personas de América Latina compartiendo tu experiencia; 
* Conectar con otras personas del equipo de mentoría y con la comunidad de los participantes, ampliando tu red profesional;
* Ganar experiencia y habilidades para realizar mentorías;
* Ganar exposición, reconocimiento y agradecimiento por tu trabajo en el programa en los espacios de rOpenSci (página web, redes sociales y eventos);
* Ayudar a rOpenSci, a la comunidad R y de Ciencia Abierta en general a crecer;
* Recibir un estipendio por tu participación en el programa.

Los mentores y mentoras seleccionados participarán en una formación sobre mentoría y logística del programa como parte de su proceso de inicio y contarán con el apoyo de la _Directora del Programa_ durante todo el programa.

## ¿Cómo aplicar?

Se debe completar el formulario de aplicación antes del _20 de Febrero de 2026_. El formulario debe completarse en _castellano_.


* [**Formulario para aplicar**](https://airtable.com/appF6OXmxkk8VmR8a/shrZnWDRKxXUEmLRM). 

## Información requerida en el formulario

A continuación detallamos toda la información que solicitamos en el formulario para que puedas prepararte antes de rellenarlo.

### Información general

* Nombre completo: _nombre(s) y apellido(s)_
* Email: _correo electrónico que quiere que usemos para comunicarnos contigo_
* País: _país de residencia_
* Zona horaria: _zona horaria de tu ciudad de residencia expresada en UTC_
* Pronombres: _por favor, comparte los pronombres que quieres que usemos para referirnos a tí (opcional)_
* GitHub o GitLab: _por favor, facilita el enlace a tu perfil_
* Redes sociales: _por favor, facilita el enlace a tu perfil de LinkedIn/Mastodon/BlueSky, etc. (opcional)_
* Sitio Web: _por favor, facilita el enlace a tu sitio web  (optional)_
* Afiliación: _por favor, indica tu afiliación a una universidad/institución/organización u otro empleador_
* Comunidad: _por favor, indica tu participación en comunidades (como R-Ladies, Grupos de Usuarios de R, RSE, LatinR, ReproHack, etc. o indica NA)_

* ¿Cómo participa en la comunidad rOpenSci? Por favor, responda en un máximo de 200 palabras.

### Experiencia

* ¿Tiene experiencia desarrollando o contribuyendo significativamente a paquetes de R? Elija una opción:

  * No, no he desarrollado ningún paquete R
  
  * No, no he desarrollado un paquete de R, pero contribuyo a uno o más paquetes de R
  
  * Sí, he desarrollado un paquete de R, pero no lo he enviado a CRAN
  
  * Sí, he desarrollado un paquete de R y está publicado en CRAN
  
  * Sí, he desarrollado un paquete de R, y pasó por el proceso de revisión de rOpenSci

* ¿Tiene experiencia en la revisión de código? 

  * No, no he revisado código
  
  * No, no he revisado código, pero he pasado por el proceso de revisión de rOpenSci
  
  * Sí, he revisado código para rOpenSci (u otra organización)
  
  * Sí, he sido editor para rOpenSci


### Información sobre tutoría

* Preferiría ser mentor/a de una persona que quiere: _Seleccione todas las que correspondan_

  * Desarrollar un nuevo paquete

  * Enviar su paquete a través del proceso de revisión de rOpenSci
  
  * Ser revisor de rOpenSci

* ¿Por qué le gustaría ser mentor/a del programa de campeones de rOpenSci? _Por favor, responda en un máximo de 200 palabras_

* Por favor, comparta un ejemplo de cuando ayudó con éxito a otra persona. _Por favor, no mencione el nombre de la(s) persona(s), sólo nos interesa saber cómo le ayudó y cuál fue el resultado_  


## Tengo más preguntas

Si tienes más preguntas chequea nuestras preguntas frecuentes o contactanos enviando un mail a info@ropensci.org.
